version: '2'

services:
  watcher:
    container_name: watcher
    image: ety001/steem-python:mysql
    volumes:
      - ./bin:/app
    env_file: .env
    restart: always
    networks:
      steem_watcher_net:
        ipv4_address: 172.22.2.3
    command: python3 -u /app/watcher.py
  
  watcher_db:
    container_name: watcher_db
    image: mariadb:latest
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      steem_watcher_net:
        ipv4_address: 172.22.2.2
  
  crond:
    container_name: crond
    image: ety001/steem-python:mysql
    volumes:
      - ./bin:/app
      - ./config/crontab:/etc/crontabs/root
      - ./logs:/var/log
    env_file: .env
    restart: always
    networks:
      steem_watcher_net:
        ipv4_address: 172.22.2.4
    command: crond -f

networks:
  steem_watcher_net:
    ipam:
      config:
        - subnet: 172.22.2.0/24
          gateway: 172.22.2.1
